version: '3'

services:
  uiowa-atr:
    build:
      context: .
      args:
        - NEXTAUTH_SECRET
        - JWT_SECRET
        - NEXTAUTH_URL
        - DATABASE_URL
        - RUNNER_ENV
    restart: always
    ports:
      - "1234:3000"
    environment:
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL
      - DATABASE_URL
      - JWT_SECRET
