version: "3"

services:
  uiowa-atr:
    build:
      context: .
    restart: always
    pull_policy: build
    ports:
      - "${PORT}:3000"
    environment:
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL
      - DATABASE_URL
      - JWT_SECRET
      - NODE_ENV
