version: '3'

services:
  uiowa-atr:
    build:
      context: .
      args:
        - NEXTAUTH_SECRET=arbitrary
        - JWT_SECRET=arbitrary
        - NEXTAUTH_URL=http://arbitrary.com
        - DATABASE_URL=http://arbitrary.com
        - RUNNER_ENV=production
    restart: always
    ports:
      - "1234:3000"
    environment:
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL
      - DATABASE_URL
      - JWT_SECRET
