# fly.toml app configuration file generated for uiowa-atr on 2024-04-23T16:22:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'uiowa-atr'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/healthcheck'

[[vm]]
  memory = '256MB'
  size = 'shared-cpu-1x'
